result_dir: "/home/cc/ai2sec/KNighter/results/ffmpeg-triage"
LLVM_dir: "/home/cc/ai2sec/KNighter/llvm-project-llvmorg-18.1.8"
target_type: "ffmpeg"
ffmpeg_dir: "/home/cc/ai2sec/KNighter/ffmpeg"
key_file: "llm_keys.yaml"
model: "gpt-5.4"
